language: python

dist: trusty

os:
  - windows
  - linux
  - osx

cache: pip

python:
  - 3.6
  - 3.7

install:
  - "pip install ."
  - "pip install --upgrade .[test]"

script:
  - pytest tests --cov=bentoml

after_success:
  - codecov
