language: python

dist: xenial

cache: pip

python:
  - 3.6
  - 3.7

install:
  - "pip freeze"
  - "pip install -U -e .[test]"
  - "pip freeze"

script:
  - pytest --cov=bentoml

after_success:
  - codecov
